# Module 03 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.3 - Subset Variables - Columns
## Agenda
- Specific Columns
- With `loc[]`
- Index Position with `iloc[]`
- Based on Data Type
- Pattern (Regex)
- Using a Boolean Mask
- Based on Column Name Length
- Condition Applied to Row Values

### 4.3.1 Selecting Specific Columns

In [2]:
# conventional import
import pandas as pd

In [3]:
# reading dataset
df = pd.read_csv("../data/diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [7]:
# Select 'Glucose', 'Insulin' and 'Age' columns
subset_df = df[['Glucose', 'Age', 'Insulin']]
subset_df

     Glucose  Age  Insulin
0        148   50        0
1         85   31        0
2        183   32        0
3         89   21       94
4        137   33      168
..       ...  ...      ...
763      101   63      180
764      122   27        0
765      121   30      112
766      126   47        0
767       93   23        0

[768 rows x 3 columns]

### 4.3.2 Selecting Columns with `loc[]`

In [8]:
# Select all rows but only 'Name' and 'Salary' columns
subset_df = df.loc[:, ['Glucose', 'BloodPressure', 'Age']]
subset_df

     Glucose  BloodPressure  Age
0        148             72   50
1         85             66   31
2        183             64   32
3         89             66   21
4        137             40   33
..       ...            ...  ...
763      101             76   63
764      122             70   27
765      121             72   30
766      126             60   47
767       93             70   23

[768 rows x 3 columns]

### 4.3.3 Selecting Columns by Index Position with `iloc[]`

In [9]:
# Select the first two columns
subset_df = df.iloc[:, :2]
subset_df

     Pregnancies  Glucose
0              6      148
1              1       85
2              8      183
3              1       89
4              0      137
..           ...      ...
763           10      101
764            2      122
765            5      121
766            1      126
767            1       93

[768 rows x 2 columns]

In [10]:
# Select columns from position 1 to 3
subset_df = df.iloc[:, 1:4]
subset_df

     Glucose  BloodPressure  SkinThickness
0        148             72             35
1         85             66             29
2        183             64              0
3         89             66             23
4        137             40             35
..       ...            ...            ...
763      101             76             48
764      122             70             27
765      121             72             23
766      126             60              0
767       93             70             31

[768 rows x 3 columns]

### 4.3.4 Selecting Columns Based on Data Type
Use the `.select_dtypes()` method to select columns of a specific data type

In [11]:
# Select only numeric columns
subset_df = df.select_dtypes(include='number')
subset_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [14]:
# Select only float columns
subset_df = df.select_dtypes(include='float')
subset_df

      BMI  DiabetesPedigreeFunction
0    33.6                     0.627
1    26.6                     0.351
2    23.3                     0.672
3    28.1                     0.167
4    43.1                     2.288
..    ...                       ...
763  32.9                     0.171
764  36.8                     0.340
765  26.2                     0.245
766  30.1                     0.349
767  30.4                     0.315

[768 rows x 2 columns]

### 4.3.5 Selecting Columns by Pattern (Regex)
Use `.filter()` to select columns matching a pattern

In [15]:
# Select columns that start with 'Ski'
subset_df = df.filter(regex='^Ski')
subset_df

     SkinThickness
0               35
1               29
2                0
3               23
4               35
..             ...
763             48
764             27
765             23
766              0
767             31

[768 rows x 1 columns]

In [17]:
# Select columns that end with 'es'
subset_df = df.filter(regex='es$')
subset_df

     Pregnancies
0              6
1              1
2              8
3              1
4              0
..           ...
763           10
764            2
765            5
766            1
767            1

[768 rows x 1 columns]

In [14]:
# Select all columns where the column name contains the letter "B" anywhere in the name
subset_df = df.filter(like='B')
subset_df

     BloodPressure   BMI
0               72  33.6
1               66  26.6
2               64  23.3
3               66  28.1
4               40  43.1
..             ...   ...
763             76  32.9
764             70  36.8
765             72  26.2
766             60  30.1
767             70  30.4

[768 rows x 2 columns]

### 4.3.6 Selecting Columns Using a Boolean Mask

In [4]:
# Select columns where the mean value is greater than 50
subset_df = df.loc[:, df.mean() > 50]
subset_df

     Glucose  BloodPressure  Insulin
0        148             72        0
1         85             66        0
2        183             64        0
3         89             66       94
4        137             40      168
..       ...            ...      ...
763      101             76      180
764      122             70        0
765      121             72      112
766      126             60        0
767       93             70        0

[768 rows x 3 columns]

In [6]:
# mean value for each column
df.mean()

Pregnancies                   3.845052
Glucose                     120.894531
BloodPressure                69.105469
SkinThickness                20.536458
Insulin                      79.799479
BMI                          31.992578
DiabetesPedigreeFunction      0.471876
Age                          33.240885
Outcome                       0.348958
dtype: float64

### 4.3.8 Selecting Columns Based on Column Name Length

In [7]:
# Select columns where the column name has more than 5 characters
subset_df = df.loc[:, df.columns.str.len() > 5]
subset_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Outcome
0,6,148,72,35,0,0.627,1
1,1,85,66,29,0,0.351,0
2,8,183,64,0,0,0.672,1
3,1,89,66,23,94,0.167,0
4,0,137,40,35,168,2.288,1
...,...,...,...,...,...,...,...
763,10,101,76,48,180,0.171,0
764,2,122,70,27,0,0.340,0
765,5,121,72,23,112,0.245,0
766,1,126,60,0,0,0.349,1
767,1,93,70,31,0,0.315,0

### 4.3.9 Selecting Columns by Condition Applied to Row Values
You can use `.any()` or `.all()` to select columns based on values in rows

In [15]:
# Select columns where any value is greater than 100
subset_df = df.loc[:, (df > 100).any()]
subset_df

     Glucose  BloodPressure  Insulin
0        148             72        0
1         85             66        0
2        183             64        0
3         89             66       94
4        137             40      168
..       ...            ...      ...
763      101             76      180
764      122             70        0
765      121             72      112
766      126             60        0
767       93             70        0

[768 rows x 3 columns]

In [16]:
# Select columns where all values are not null
subset_df = df.loc[:, df.notnull().all()]
subset_df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*