# Module 03 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.4 - Subsets - Rows and Columns & New Columns
## Agenda
- Selecting Specific Rows and Columns
- Creating New Columns
  - With constant values
  - Using `.assign()`
  - Using normal calculation
  - Using `.apply()` & `lambda`
  - Using `.loc`
  - Using `.query()`
  - Using `.isin()`
- Drop Specific Columns

In [1]:
#conventional import
import pandas as pd

In [2]:
# reading dataset
df = pd.read_csv("../data/LungCapData.csv")
df

     LungCap  Age  Height Smoke  Gender Caesarean
0      6.475    6    62.1    no    male        no
1     10.125   18    74.7   yes  female        no
2      9.550   16    69.7    no  female       yes
3     11.125   14    71.0    no    male        no
4      4.800    5    56.9    no    male        no
..       ...  ...     ...   ...     ...       ...
720    5.725    9    56.0    no  female        no
721    9.050   18    72.0   yes    male       yes
722    3.850   11    60.5   yes  female        no
723    9.825   15    64.9    no  female        no
724    7.100   10    67.7    no    male        no

[725 rows x 6 columns]

## 4.4.1 Selecting Specific Rows and Columns

In [3]:
# Select rows where Age > 10 and include only 'Age','LungCap', 'Height', 'Gender' columns
subset_df = df.loc[df['Age'] > 10, ['Age','LungCap', 'Height', 'Gender']]
subset_df

     Age  LungCap  Height  Gender
1     18   10.125    74.7  female
2     16    9.550    69.7  female
3     14   11.125    71.0    male
5     11    6.225    58.7  female
7     11    7.325    70.4    male
..   ...      ...     ...     ...
717   16    8.825    71.3  female
718   17    7.175    68.8    male
721   18    9.050    72.0    male
722   11    3.850    60.5  female
723   15    9.825    64.9  female

[492 rows x 4 columns]

### 4.4.2 Creating New Columns

### 4.4.2.1 Create a column with a constant value

In [4]:
# Add a new column with a constant value of 0
df['NewColumn'] = 0
df

     LungCap  Age  Height Smoke  Gender Caesarean  NewColumn
0      6.475    6    62.1    no    male        no          0
1     10.125   18    74.7   yes  female        no          0
2      9.550   16    69.7    no  female       yes          0
3     11.125   14    71.0    no    male        no          0
4      4.800    5    56.9    no    male        no          0
..       ...  ...     ...   ...     ...       ...        ...
720    5.725    9    56.0    no  female        no          0
721    9.050   18    72.0   yes    male       yes          0
722    3.850   11    60.5   yes  female        no          0
723    9.825   15    64.9    no  female        no          0
724    7.100   10    67.7    no    male        no          0

[725 rows x 7 columns]

### 4.4.2.2 Using `.assign()` to Add a New Column

In [5]:
# Add a column using assign; can also chain this with other operations
df = df.assign(Height_cm=df['Height'] * 2.54)
df

     LungCap  Age  Height Smoke  Gender Caesarean  NewColumn  Height_cm
0      6.475    6    62.1    no    male        no          0    157.734
1     10.125   18    74.7   yes  female        no          0    189.738
2      9.550   16    69.7    no  female       yes          0    177.038
3     11.125   14    71.0    no    male        no          0    180.340
4      4.800    5    56.9    no    male        no          0    144.526
..       ...  ...     ...   ...     ...       ...        ...        ...
720    5.725    9    56.0    no  female        no          0    142.240
721    9.050   18    72.0   yes    male       yes          0    182.880
722    3.850   11    60.5   yes  female        no          0    153.670
723    9.825   15    64.9    no  female        no          0    164.846
724    7.100   10    67.7    no    male        no          0    171.958

[725 rows x 8 columns]

In [9]:
# Filter rows where 'BMI' is greater than equal 23 and add a new column with a calculated value
subset_df = df[df['Gender'] == 'male'].assign(height_in_meter=df['Height_cm'] / 100)
subset_df

,LungCap,Age,Height,Smoke,Gender,Caesarean,NewColumn,Height_cm,height_multiply_age,height_in_meter
0,6.475,6,62.1,no,male,no,0,157.734,372.6,1.57734
3,11.125,14,71.0,no,male,no,0,180.340,994.0,1.80340
4,4.800,5,56.9,no,male,no,0,144.526,284.5,1.44526
6,4.950,8,63.3,no,male,yes,0,160.782,506.4,1.60782
7,7.325,11,70.4,no,male,no,0,178.816,774.4,1.78816
...,...,...,...,...,...,...,...,...,...,...
716,7.075,11,66.7,no,male,yes,0,169.418,733.7,1.69418
718,7.175,17,68.8,no,male,yes,0,174.752,1169.6,1.74752
719,7.325,9,66.3,no,male,no,0,168.402,596.7,1.68402
721,9.050,18,72.0,yes,male,yes,0,182.880,1296.0,1.82880
724,7.100,10,67.7,no,male,no,0,171.958,677.0,1.71958

### 4.4.2.3 Using Existing Columns to Create a Calculated Column

In [7]:
# Add a column that is the product of two existing columns
df['height_multiply_age'] = df['Height'] * df['Age']
df

,LungCap,Age,Height,Smoke,Gender,Caesarean,NewColumn,Height_cm,height_multiply_age
0,6.475,6,62.1,no,male,no,0,157.734,372.6
1,10.125,18,74.7,yes,female,no,0,189.738,1344.6
2,9.550,16,69.7,no,female,yes,0,177.038,1115.2
3,11.125,14,71.0,no,male,no,0,180.340,994.0
4,4.800,5,56.9,no,male,no,0,144.526,284.5
...,...,...,...,...,...,...,...,...,...
720,5.725,9,56.0,no,female,no,0,142.240,504.0
721,9.050,18,72.0,yes,male,yes,0,182.880,1296.0
722,3.850,11,60.5,yes,female,no,0,153.670,665.5
723,9.825,15,64.9,no,female,no,0,164.846,973.5
724,7.100,10,67.7,no,male,no,0,171.958,677.0

### 4.4.2.4 Adding a Column Based on Conditions with `.apply()` and `lambda`

In [12]:
# Add a new column based on conditions
df['Caesarean_Number'] = df['Caesarean'].apply(lambda x: 1 if x == 'yes' else 0)
df

,LungCap,Age,Height,Smoke,Gender,Caesarean,NewColumn,Height_cm,height_multiply_age,Caesarean_Number
0,6.475,6,62.1,no,male,no,0,157.734,372.6,0
1,10.125,18,74.7,yes,female,no,0,189.738,1344.6,0
2,9.550,16,69.7,no,female,yes,0,177.038,1115.2,1
3,11.125,14,71.0,no,male,no,0,180.340,994.0,0
4,4.800,5,56.9,no,male,no,0,144.526,284.5,0
...,...,...,...,...,...,...,...,...,...,...
720,5.725,9,56.0,no,female,no,0,142.240,504.0,0
721,9.050,18,72.0,yes,male,yes,0,182.880,1296.0,1
722,3.850,11,60.5,yes,female,no,0,153.670,665.5,0
723,9.825,15,64.9,no,female,no,0,164.846,973.5,0
724,7.100,10,67.7,no,male,no,0,171.958,677.0,0

### 4.4.2.5 Create Columns Using `.loc`

In [20]:
# Add column based on a condition
df.loc[df['Age'] > 19, 'Status'] = 'Non Teen'
df.loc[df['Age'] > 12 & (df['Age'] <= 19), 'Status'] = 'Teen'
df.loc[df['Age'] < 12, 'Status'] = 'Child'
df

,LungCap,Age,Height,Smoke,Gender,Caesarean,NewColumn,Height_cm,height_multiply_age,Caesarean_Number,Status
0,6.475,6,62.1,no,male,no,0,157.734,372.6,0,Child
1,10.125,18,74.7,yes,female,no,0,189.738,1344.6,0,Teen
2,9.550,16,69.7,no,female,yes,0,177.038,1115.2,1,Teen
3,11.125,14,71.0,no,male,no,0,180.340,994.0,0,Teen
4,4.800,5,56.9,no,male,no,0,144.526,284.5,0,Child
...,...,...,...,...,...,...,...,...,...,...,...
720,5.725,9,56.0,no,female,no,0,142.240,504.0,0,Child
721,9.050,18,72.0,yes,male,yes,0,182.880,1296.0,1,Teen
722,3.850,11,60.5,yes,female,no,0,153.670,665.5,0,Child
723,9.825,15,64.9,no,female,no,0,164.846,973.5,0,Teen
724,7.100,10,67.7,no,male,no,0,171.958,677.0,0,Child

### 4.4.2.6 Create Columns using `.query()`

In [27]:
subset_df = df.query('Age < 15').assign(need_care=lambda x: x['Smoke'] == 'yes')
subset_df

,LungCap,Age,Height,Smoke,Gender,Caesarean,Height_cm,height_multiply_age,Caesarean_Number,Status,need_care
0,6.475,6,62.1,no,male,no,157.734,372.6,0,Child,False
3,11.125,14,71.0,no,male,no,180.340,994.0,0,Teen,False
4,4.800,5,56.9,no,male,no,144.526,284.5,0,Child,False
5,6.225,11,58.7,no,female,no,149.098,645.7,0,Child,False
6,4.950,8,63.3,no,male,yes,160.782,506.4,1,Child,False
...,...,...,...,...,...,...,...,...,...,...,...
716,7.075,11,66.7,no,male,yes,169.418,733.7,1,Child,False
719,7.325,9,66.3,no,male,no,168.402,596.7,0,Child,False
720,5.725,9,56.0,no,female,no,142.240,504.0,0,Child,False
722,3.850,11,60.5,yes,female,no,153.670,665.5,0,Child,True
724,7.100,10,67.7,no,male,no,171.958,677.0,0,Child,False

**Explanation**
1. **`df.query('Age < 15')`**: This filters the rows in `df` where the column `Age` is less than 15, creating a subset of `df`.

2. **`.assign(need_care=lambda x: x['Smoke'] == 'yes')`**: The `.assign()` method adds a new column, `need_care`, to the subset. It uses a lambda function that checks if the value in the `Smoke` column is `'yes'`. If `Smoke` is `'yes'`, `need_care` will be `True`; otherwise, it will be `False`.

The resulting DataFrame, `subset_df`, contains only rows where `Age` is less than 15 and includes an additional `need_care` column based on whether `Smoke` is `'yes'`.

### 4.4.2.7 Create Columns using `.isin()`

In [28]:
covid_df = pd.read_csv("../data/covid19.csv")
covid_df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0
306426,306427,05/29/2021,Zhejiang,Mainland China,2021-05-30 04:20:55,1364.0,1.0,1324.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0

In [41]:
# Select rows where Country/Region is either 'Ukrain' or 'Netherlands', add a "death_affected_ratio" column
subset_df = covid_df[covid_df['Country/Region'].isin(['Ukraine', 'Netherlands'])].assign(death_affected_ratio=lambda x: x['Deaths'] / x['Confirmed'])
subset_df

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered,death_affected_ratio
2640,2641,02/27/2020,NaN,Netherlands,2020-02-27T21:13:10,1.0,0.0,0.0,0.000000
2755,2756,02/28/2020,NaN,Netherlands,2020-02-28T01:23:03,1.0,0.0,0.0,0.000000
2836,2837,02/29/2020,NaN,Netherlands,2020-02-29T18:03:05,6.0,0.0,0.0,0.000000
2954,2955,03/01/2020,NaN,Netherlands,2020-03-01T15:33:03,10.0,0.0,0.0,0.000000
3075,3076,03/02/2020,NaN,Netherlands,2020-03-02T20:53:02,18.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...
306423,306424,05/29/2021,Zakarpattia Oblast,Ukraine,2021-05-30 04:20:55,61611.0,1586.0,58882.0,0.025742
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,2021-05-30 04:20:55,102641.0,2335.0,95289.0,0.022749
306425,306426,05/29/2021,Zeeland,Netherlands,2021-05-30 04:20:55,29147.0,245.0,0.0,0.008406
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,2021-05-30 04:20:55,87550.0,1738.0,83790.0,0.019852
306428,306429,05/29/2021,Zuid-Holland,Netherlands,2021-05-30 04:20:55,391559.0,4252.0,0.0,0.010859

### 4.4.3 Drop specific columns

In [43]:
# Select rows where Deaths > 100, keep all columns except "Recovered" and "Last Update"
subset_df = covid_df.loc[covid_df['Deaths'] > 100].drop(columns=['Recovered', 'Last Update'])
subset_df

,SNo,ObservationDate,Province/State,Country/Region,Confirmed,Deaths
279,280,01/28/2020,Hubei,Mainland China,3554.0,125.0
333,334,01/29/2020,Hubei,Mainland China,3554.0,125.0
389,390,01/30/2020,Hubei,Mainland China,4903.0,162.0
449,450,01/31/2020,Hubei,Mainland China,5806.0,204.0
513,514,02/01/2020,Hubei,Mainland China,7153.0,249.0
...,...,...,...,...,...,...
306423,306424,05/29/2021,Zakarpattia Oblast,Ukraine,61611.0,1586.0
306424,306425,05/29/2021,Zaporizhia Oblast,Ukraine,102641.0,2335.0
306425,306426,05/29/2021,Zeeland,Netherlands,29147.0,245.0
306427,306428,05/29/2021,Zhytomyr Oblast,Ukraine,87550.0,1738.0
306428,306429,05/29/2021,Zuid-Holland,Netherlands,391559.0,4252.0

  *Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*