# Module 03 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.5 - Handling Missing Values
## Agenda
- Intro to NA Values
- Removing Missing Values
- Replacing Missing Values
- Handling / Removing Duplicates
- Outliers Detection and Removal

In [1]:
#conventional import
import pandas as pd

In [23]:
#read data
df = pd.read_csv('../data/covid19.csv')

In [3]:
df.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [5]:
# get information about dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   SNo              306429 non-null  int64
 1   ObservationDate  306429 non-null  object
 2   Province/State   228326 non-null  object
 3   Country/Region   306429 non-null  object
 4   Last Update      306429 non-null  object
 5   Confirmed        306429 non-null  float64
 6   Deaths           306429 non-null  float64
 7   Recovered        306429 non-null  float64
dtypes: float64(3), int64(1), object(4)
memory usage: 18.7+ MB

### 4.5.1 Introduction to NA values

In [6]:
# check missing values 
df.isnull()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
306424,False,False,False,False,False,False,False,False
306425,False,False,False,False,False,False,False,False
306426,False,False,False,False,False,False,False,False
306427,False,False,False,False,False,False,False,False
306428,False,False,False,False,False,False,False,False

In [10]:
# check missing values for each rows and columns
df.isna()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
306424,False,False,False,False,False,False,False,False
306425,False,False,False,False,False,False,False,False
306426,False,False,False,False,False,False,False,False
306427,False,False,False,False,False,False,False,False
306428,False,False,False,False,False,False,False,False

In [8]:
# column wise null value count
df.isnull().sum()

SNo                    0
ObservationDate        0
Province/State     78103
Country/Region         0
Last Update            0
Confirmed              0
Deaths                 0
Recovered              0
dtype: int64

In [9]:
df.isna()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
306424,False,False,False,False,False,False,False,False
306425,False,False,False,False,False,False,False,False
306426,False,False,False,False,False,False,False,False
306427,False,False,False,False,False,False,False,False
306428,False,False,False,False,False,False,False,False

In [13]:
# column wise null value counts
df.isna().sum(axis = 0)

SNo                    0
ObservationDate        0
Province/State     78103
Country/Region         0
Last Update            0
Confirmed              0
Deaths                 0
Recovered              0
dtype: int64

In [14]:
# if the rows contains any null value or not
df.isna().any(axis = 1)

0         False
1         False
2         False
3         False
4         False
          ...
306424    False
306425    False
306426    False
306427    False
306428    False
Length: 306429, dtype: bool

In [16]:
# the inverse of isna()
df.notna()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
306424,True,True,True,True,True,True,True,True
306425,True,True,True,True,True,True,True,True
306426,True,True,True,True,True,True,True,True
306427,True,True,True,True,True,True,True,True
306428,True,True,True,True,True,True,True,True

###  4.5.2 Removing Missing values

In [19]:
# each category count
df['Province/State'].value_counts(dropna = False)

Province/State
NaN                             78103
Unknown                          4123
Amazonas                         1109
Diamond Princess cruise ship      924
Grand Princess                    882
                                ...
Collin County, TX                   1
Bennington County, VT               1
Harrison County, KY                 1
Carver County, MN                   1
Dadar Nagar Haveli                  1
Name: count, Length: 737, dtype: int64

In [20]:
df.dropna(inplace=True)

- removing missing values using `.dropna()`
- **inplace = True** make this change in the existing df

In [22]:
# count null values for each column
df.isnull().sum()

SNo                0
ObservationDate    0
Province/State     0
Country/Region     0
Last Update        0
Confirmed          0
Deaths             0
Recovered          0
dtype: int64

In [36]:
#read data
df = pd.read_csv('../data/covid19.csv')

In [25]:
df.shape

(306429, 8)

In [27]:
# delete rows if any column contains null values
df.dropna(axis = 0, how = "any").shape

(228326, 8)

In [30]:
# delete columns if any rows contains null values
df.dropna(axis = 1, how = "any").shape

(306429, 7)

In [33]:
# delete rows if all column contains null values
df.dropna(axis = 0, how = "all").shape

(306429, 8)

In [34]:
# delete columns if all rows contains null values
df.dropna(axis = 1, how = "all").shape

(306429, 8)

In [43]:
# if any rows have at least 5 non null values, it will remain in df
df.dropna(axis = 0, thresh = 5).shape

(306429, 8)

- **`axis=0`**: Indicates that the operation is performed on rows. If set to 1, it would apply to columns.
- **`thresh=8`**: Ensures that only rows with at least 5 non-null values remain. Rows with fewer than 5 non-null entries are dropped.

In [46]:
# if any of this mentioned column contains null values, the row will drop
df.dropna(axis = 0, subset = ["Confirmed", "Deaths", "Recovered"], how = "any").shape

(306429, 8)

### 4.5.3 Replacing Missing Values with `fillna()`

In [68]:
# read titanic data
df = pd.read_csv('../data/titanic.csv')

In [51]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [54]:
# get info about this df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [55]:
#count null value for each column
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [65]:
# get mean of age column and round it to 1 decimal place
mean = df.Age.mean()
mean = round(mean, 1)
mean

np.float64(29.7)

1. **`titanic.age.mean()`**: This calculates the mean (average) of the values in the `age` column of the `titanic` DataFrame.
2. **`round(..., 1)`**: The mean value is rounded to one decimal place using the `round()` function.
3. **`mean`**: Stores the rounded mean age value for easy reference or further calculations.

The output shows the average age of passengers on the Titanic, rounded to one decimal place.

In [62]:
# fill the null value of 'Age' column with 'mean'
df.Age.fillna(mean, inplace = True)

/tmp/ipykernel_9477/2206513159.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(mean, inplace = True)

In [64]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [67]:
# get median of age column and round it to 1 decimal place
median = df.Age.median()
median = round(median, 1)
median

np.float64(29.7)

In [69]:
# fill the null value of 'Age' column with 'median'
df.Age.fillna(median, inplace = True)

/tmp/ipykernel_9477/1534543321.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(median, inplace = True)

### 4.5.4 Handling / Removing Duplicates

In [73]:
# create a dummy dataframe
alphabet = pd.DataFrame(["a", "b", "c", "c", "d", "e", "f", "g", "g", "g"], columns = ["Alphabet"])
alphabet

  Alphabet
0        a
1        b
2        c
3        c
4        d
5        e
6        f
7        g
8        g
9        g

In [75]:
# check which row contain duplicate
alphabet.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8     True
9     True
dtype: bool

In [82]:
# count duplicate values
alphabet.duplicated().sum()

np.int64(3)

#### drop duplicates using `.drop_duplicates()`

#drop duplicate values
alphabet.drop_duplicates()

In [87]:
# again check duplicate values deleted or not
alphabet.duplicated().sum()

np.int64(0)

In [86]:
#drop duplicate values in existing dataframe
alphabet.drop_duplicates(inplace=True)

### 4.5.5 Outliers Detection and Removal
An `outlier` is a data point significantly different from other observations in a dataset. Outliers can occur due to variability in the data, errors in data collection, or unexpected values and can skew statistical analysis, leading to misleading results

#### 4.5.5.1 Outliers Detection and Removal using `IQR`

In [88]:
df = pd.read_table("../data/pulse.txt")
df.head()

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93

- **Q1 (First Quartile)**: The 25th percentile, or the "lower quartile."
  - Represents the value below which 25% of the data fall.

- **Q2 (Second Quartile)**: The 50th percentile, also known as the **median**.
  - Represents the value below which 50% of the data fall.

- **Q3 (Third Quartile)**: The 75th percentile, or the "upper quartile."
  - Represents the value below which 75% of the data fall.

These quartiles are used in calculating the **Interquartile Range (IQR)**, which is often applied to detect **outliers**:

**IQR = Q3 - Q1**

Values below **( Q1 - 1.5*IQR )** or above **( Q3 + 1.5 *IQR )** are typically considered outliers.

In [89]:
# calculate quantile 
Q1, Q2, Q3 = df['Height'].quantile([.25, .50, .75])
print("Q1 25 percentile of the given data is: ", Q1)
print("Q2 50 percentile of the given data is: ", Q2)
print("Q3 75 percentile of the given data is: ", Q3)

Q1 25 percentile of the given data is:  166.0
Q2 50 percentile of the given data is:  173.0
Q3 75 percentile of the given data is:  180.0

In [91]:
# find range
r = df.Height.max() - df.Height.min() 
print(r)

55

In [92]:
# interquartile range (iqr)
IQR = Q3 - Q1 
print(IQR)

14.0

In [93]:
# set upper and lower limit [Q1 - 1.5 x IQR, Q3 + 1.5 x IQR]
lower = Q1 - 1.5 * IQR 
upper = Q3 + 1.5 * IQR 
lower, upper

(145.0, 201.0)

In [94]:
df.shape

(108, 11)

In [95]:
# detect & removal outliers 
df_new = df[(df['Height'] < upper) & (df['Height'] > lower)]
df_new

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93
...,...,...,...,...,...,...,...,...,...,...,...
103,163,47.0,23,2,1,1,3,1,71.0,125.0,98
104,161,43.0,19,2,2,2,3,2,90.0,89.0,98
105,182,60.0,22,1,2,1,3,2,86.0,84.0,98
106,170,65.0,18,1,2,1,1,2,69.0,64.0,98
107,185,85.0,19,1,2,1,2,2,75.0,68.0,98

In [96]:
df_new.shape

(107, 11)

#### 4.5.5.2 Outliers Detection and Removal using `Percentile`

In [97]:
df = pd.read_table("../data/pulse.txt")

In [98]:
df.head()

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93

In [99]:
# set maximum thresold 
max_thresold = df['Height'].quantile(0.95)
max_thresold

np.float64(189.64999999999998)

In [100]:
# detect outliers 
df[df['Height'] > max_thresold]

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
71,190,82.0,19,1,2,2,2,2,76.0,73.0,97
79,191,78.0,19,1,2,1,1,1,68.0,136.0,97
83,194,110.0,25,1,2,2,2,2,75.0,75.0,97
85,192,105.0,21,1,2,2,2,2,80.0,73.0,97
86,194,95.0,18,1,2,1,2,1,84.0,140.0,97

In [101]:
# set minimum thresold 
min_thresold = df['Height'].quantile(0.05)
min_thresold

np.float64(157.35)

In [102]:
# detect outliers 
df[df['Height'] < min_thresold]

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
19,155,50.0,19,2,2,2,2,2,78.0,79.0,93
21,140,50.0,34,2,2,2,3,1,70.0,98.0,93
39,155,49.0,18,2,2,1,2,2,104.0,92.0,95
50,157,41.0,20,2,2,2,2,1,70.0,95.0,96
69,151,42.0,22,2,2,2,3,1,85.0,130.0,97
98,155,55.0,20,2,2,1,1,2,82.0,87.0,98

In [103]:
# remove outliers 
df_clean = df[(df['Height'] < max_thresold) & (df['Height'] > min_thresold)]
df_clean

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93
5,184,74.0,22,1,2,1,3,1,78.0,141.0,93
...,...,...,...,...,...,...,...,...,...,...,...
103,163,47.0,23,2,1,1,3,1,71.0,125.0,98
104,161,43.0,19,2,2,2,3,2,90.0,89.0,98
105,182,60.0,22,1,2,1,3,2,86.0,84.0,98
106,170,65.0,18,1,2,1,1,2,69.0,64.0,98
107,185,85.0,19,1,2,1,2,2,75.0,68.0,98

In [104]:
# shape of dataset 
df.shape, df_clean.shape

((108, 11), (96, 11))

#### 4.5.5.3 Outliers Detection and Removal using `z-score`

$$
Z = \frac{x - \mu}{\sigma}
$$

In [105]:
df['ZScore'] = (df.Height - df.Height.mean())/df.Height.std() 
df.head()

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year,ZScore
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93,-0.026530
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93,0.566278
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93,-0.619338
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93,2.147098
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93,-0.026530

In [106]:
# detect 
df[(df['ZScore'] < -3) | df['ZScore'] > 3]

Empty DataFrame
Columns: [Height, Weight, Age, Gender, Smokes, Alcohol, Exercise, Ran, Pulse1, Pulse2, Year, ZScore]
Index: []

In [107]:
# removal 
df_new = df[(df['ZScore'] > -3) | df['ZScore'] < 3]
df_new

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year,ZScore
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93,-0.026530
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93,0.566278
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93,-0.619338
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93,2.147098
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93,-0.026530
...,...,...,...,...,...,...,...,...,...,...,...,...
103,163,47.0,23,2,1,1,3,1,71.0,125.0,98,-1.014543
104,161,43.0,19,2,2,2,3,2,90.0,89.0,98,-1.212145
105,182,60.0,22,1,2,1,3,2,86.0,84.0,98,0.862682
106,170,65.0,18,1,2,1,1,2,69.0,64.0,98,-0.322934
107,185,85.0,19,1,2,1,2,2,75.0,68.0,98,1.159085

In [108]:
df.shape[0] - df_new.shape[0]

0

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*